#!/usr/bin/env python3
"""resolve_forecastbench.py — close the 32 open `forecastbench` ACLED entries.

The 2025-10-26 ForecastBench round resolved on 2025-11-02. Chorus already
scored these questions internally — the resolved outcomes live in
`~/chorus/outputs/forecastbench/2025-10-26_chorus_full_v10.json` under
`per_question` (fields: question, actual, brier, resolution_date). The
canonical ledger never had the resolutions written back to it.

This resolver does the join: match each open `domain == "forecastbench"`
ledger entry to its `per_question` row by question-text prefix, then
update the canonical record.

Fields written on resolve:
  status            "open" -> "resolved"
  resolved_at       now (UTC, iso)
  resolution        per_question.actual (0.0 or 1.0)
  brier_score       per_question.brier
  resolution_source "forecastbench:2025-10-26_round / chorus_full_v10"
  audit_flags       drops "resolution_overdue"

DRY-RUN BY DEFAULT — pass --commit to write.

Concurrency: the chorus-public-ledger repo is touched by parallel Claude
sessions. Always `git status` the ledger file before --commit, and prefer
to land the change in a single commit you stage manually rather than
letting any automation push.
"""
from __future__ import annotations

import argparse
import json
from datetime import datetime, timezone
from pathlib import Path

DEFAULT_LEDGER = Path("/Users/addieconner/chorus-public-ledger/ledger_canonical.json")
DEFAULT_PQ = Path("/Users/addieconner/chorus/outputs/forecastbench/2025-10-26_chorus_full_v10.json")
RESOLUTION_SOURCE = "forecastbench:2025-10-26_round / chorus_full_v10"
PREFIX_LEN = 250  # question-text join key length


def load_pq(pq_path: Path) -> dict[str, dict]:
    data = json.loads(pq_path.read_text())
    return {(q.get("question") or "")[:PREFIX_LEN]: q for q in data.get("per_question", [])}


def matches(preds: list[dict], pq_map: dict[str, dict]) -> list[tuple[dict, dict]]:
    out = []
    for p in preds:
        if p.get("domain") != "forecastbench" or p.get("status") != "open":
            continue
        key = (p.get("question") or "")[:PREFIX_LEN]
        q = pq_map.get(key)
        if q is None or q.get("actual") is None:
            continue
        out.append((p, q))
    return out


def apply_resolution(pred: dict, q: dict, now_iso: str) -> dict:
    # Brier MUST be recomputed from the ledger's chorus_probability — the
    # per_question file is generated by a specific chorus_full version and
    # may carry a different `predicted` for the same question.
    p = pred.get("chorus_probability")
    actual = q["actual"]
    pred["status"] = "resolved"
    pred["resolved_at"] = now_iso
    pred["resolution"] = actual
    pred["brier_score"] = round((p - actual) ** 2, 6) if p is not None else None
    pred["resolution_source"] = RESOLUTION_SOURCE
    flags = [f for f in (pred.get("audit_flags") or []) if f != "resolution_overdue"]
    pred["audit_flags"] = flags
    return pred


def main() -> None:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--ledger", type=Path, default=DEFAULT_LEDGER)
    ap.add_argument("--per-question", type=Path, default=DEFAULT_PQ,
                    help="forecastbench output file with per_question array (default: 2025-10-26 chorus_full_v10)")
    ap.add_argument("--commit", action="store_true",
                    help="write changes back to --ledger (default: dry-run, print only)")
    args = ap.parse_args()

    preds = json.loads(args.ledger.read_text())
    pq_map = load_pq(args.per_question)
    pairs = matches(preds, pq_map)

    print(f"ledger:        {args.ledger}")
    print(f"per_question:  {args.per_question}")
    print(f"open forecastbench entries: {sum(1 for p in preds if p.get('domain')=='forecastbench' and p.get('status')=='open')}")
    print(f"matched to per_question:    {len(pairs)}")
    print()
    print(f"{'canonical_id':<22} {'p':>6} {'actual':>7} {'brier':>7}  question")
    print("-" * 100)
    sum_brier = 0.0
    for p, q in pairs:
        p_pred = p.get("chorus_probability")
        # Recompute brier from ledger's own probability (see apply_resolution comment)
        b = (p_pred - q["actual"]) ** 2 if p_pred is not None else 0.0
        sum_brier += b
        qtext = (p.get("question") or "").split("\n")[0][:60]
        print(f"{p['canonical_id']:<22} {p_pred:>6.3f} {q['actual']:>7.1f} {b:>7.4f}  {qtext}")
    if pairs:
        print(f"\nmean Brier across {len(pairs)} resolves: {sum_brier/len(pairs):.4f}")

    if not args.commit:
        print("\n[DRY-RUN] no file written. Re-run with --commit to apply.")
        return

    now_iso = datetime.now(timezone.utc).isoformat(timespec="seconds")
    for p, q in pairs:
        apply_resolution(p, q, now_iso)
    args.ledger.write_text(json.dumps(preds, indent=2) + "\n")
    print(f"\n[COMMITTED] {len(pairs)} entries resolved in {args.ledger}.")
    print("Review with: git diff ledger_canonical.json")


if __name__ == "__main__":
    main()
